export const TableData = [
  {
    Process: "Application review",
    user: [
      "/assets/images/1.png",
      "/assets/images/2.png",
      "/assets/images/3.png",
      "/assets/images/4.png",
      "/assets/images/5.png",
    ],
    Progress: 27,
    Status: "Active",
    Date: "19.10.2019",
  },
  {
    Process: "Credit assessment",
    user: [
      "/assets/images/1.png",
      "/assets/images/2.png",
      "/assets/images/3.png",
      "/assets/images/4.png",
      "/assets/images/5.png",
    ],
    Progress: 27,
    Status: "Active",
    Date: "19.10.2019",
  },
  {
    Process: "KYC",
    user: [
      "/assets/images/1.png",
      "/assets/images/2.png",
      "/assets/images/3.png",
      "/assets/images/4.png",
      "/assets/images/5.png",
    ],
    Progress: 27,
    Status: "Active",
    Date: "19.10.2019",
  },
  {
    Process: "Account opened",
    user: [
      "/assets/images/1.png",
      "/assets/images/2.png",
      "/assets/images/3.png",
      "/assets/images/4.png",
      "/assets/images/5.png",
    ],
    Progress: 27,
    Status: "Active",
    Date: "19.10.2019",
  },
  {
    Process: "Transaction documents review",
    user: [
      "/assets/images/1.png",
      "/assets/images/2.png",
      "/assets/images/3.png",
      "/assets/images/4.png",
      "/assets/images/5.png",
    ],
    Progress: 27,
    Status: "Active",
    Date: "19.10.2019",
  },
  {
    Process: "Disbursement of loan facility",
    user: [
      "/assets/images/1.png",
      "/assets/images/2.png",
      "/assets/images/3.png",
      "/assets/images/4.png",
      "/assets/images/5.png",
    ],
    Progress: 27,
    Status: "Active",
    Date: "19.10.2019",
  },
];
