#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=`git rev-parse --abbrev-ref HEAD`
if [$current_branch == master|main]
then
    echo "⚠️ Please don't commit directly to $current_branch."
    false;
fi

echo '🏗️👷 Styling, testing and building your project before committing'
npm run format
# Check Prettier standards
npm run check-format ||
(
    echo '❌ Prettier Check Failed ❌. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '❌ ESLint Check Failed ❌. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed Type check ❌ Make the changes required above.'
    false;
)

