#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "⚠️ You can't commit directly to master branch"
  exit 1
fi

echo '🏗️👷 Styling, testing and building your project before committing'
npm run format
# Check Prettier standards
npm run check-format ||
(
    echo '❌ Prettier Check Failed ❌. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '❌ ESLint Check Failed ❌. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed Type check ❌ Make the changes required above.'
    false;
)

